spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CashCard
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090
